---
- name: debug
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: debug variable
      debug:
        var: debug_var
        
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5        

    - name: debug variable
      debug:
        var: debug_var
